### ISSUE TITLE
socket.error delaying RecvGCM

### ISSUE THREAD

**Issue by Krysher** [vesche/basicRAT#15]
```
    def recvGCM(self):
        m = ''
        while True:
            try:
                m += self.conn.recv(4096)
            except socket.error:            <<<<<<<<
                break                              <<<<<<<<

        # prevents decryption of empty string
        if not m:
            return m

        IV = crypto.bytes_to_long(m[:12])
        ciphertext = m[12:-16]
        tag = crypto.bytes_to_long(m[-16:])

        return self.GCM.decrypt(IV, ciphertext, tag)
```

Except socket.error is somehow lagging the respond by about 1/3 of a second.  Not sure why. Moving the decryption before that and response happen instantly.

**Comment by vesche** [comment]
Most likely because that `socket.error` is the only time socket is called in `common.py` and it lags a bit when the socket library is loaded. Although it would be sloppy, it would probably fixed if I did something like this:

```
try:
    m += self.conn.recv(4096)
except:
    break 
```

I'm going to keep this open for now and do some testing when I get a chance. Thanks for pointing this out.

**Comment by vesche** [comment]
I've rolled back to AES-256 D-H without GCM. For the time being this should no longer be a problem. If GCM support is still desired, work can be conducted in the output branch. More here: #21
