### ISSUE TITLE
file transfer padding issue

### ISSUE THREAD

**Issue by deadPix3l** [vesche/basicRAT#2]
occasionally sending a file in either direction will fail with padding errors

# Resolution
- Find the error
- create a unit test for the future
- create a simulated failure to test the patch

**Comment by vesche** [comment]
This is still an issue using GCM. ASCII files can be downloaded client to server without issue. Binary files **cannot** be downloaded, produces an `InvalidTagException`. Uploading ASCII files server to client is inconsistent at best and either has odd non-ASCII trailing characters or produces `InvalidInputException`. Uploading in general has an added challenge of incrementing IV's in `filesock.py`...

It's also worth noting that doing an upload causes the client to receive a large amount of data, which is typically what the server does. The only other time the client receives data is the initial prompt (a small amount of data). Similar to how we had to integrate `s.settimeout(value)` for the server (because it receives a lot of data) we may need to do something similar here.

**Comment by deadPix3l** [comment]
sendGCM and recvGCM are about to undergo a major rework on devel branch, to address this issue. I believe the issue is caused by encrypting 4096 bytes and then sending 4096 bytes, not accounting for the additional data (the iv and the tag). testing will be done!

**Comment by vesche** [comment]
I've rolled back to AES-256 D-H without GCM. For the time being this should no longer be a problem. If GCM support is still desired, work can be conducted in the output branch. More here: #21
