### ISSUE TITLE
core.aes_gcm.InvalidTagException: The authentication tag is invalid.

### ISSUE THREAD

**Issue by cyankw** [vesche/basicRAT#20]
Platform: windows10
[?] basicRAT> clients
ID - Client Address
 1 - 127.0.0.1

[?] basicRAT> client 1
Client 1 selected.

[1] basicRAT> survey
Running survey...
Traceback (most recent call last):
  File "C:\Users\lenovo-df\Desktop\PYN\basicRAT-master\basicRAT_server.py", line 226, in <module>
    main()
  File "C:\Users\lenovo-df\Desktop\PYN\basicRAT-master\basicRAT_server.py", line 213, in main
    client.send(prompt)
  File "C:\Users\lenovo-df\Desktop\PYN\basicRAT-master\basicRAT_server.py", line 128, in send
    recv_data = self.recvGCM().rstrip()
  File "C:\Users\lenovo-df\Desktop\PYN\basicRAT-master\core\common.py", line 52, in recvGCM
    return self.GCM.decrypt(IV, ciphertext, tag)
  File "C:\Users\lenovo-df\Desktop\PYN\basicRAT-master\core\aes_gcm.py", line 160, in decrypt
    raise InvalidTagException
core.aes_gcm.InvalidTagException: The authentication tag is invalid.

This situation happens sometimes, but sometimes, the survey can be used correctly

**Comment by deadPix3l** [comment]
The InvalidTagException happens sometimes and it is a known error. @vesche is currently stripping all the crypto to start from scratch, while I am trying to debug it. This is an extremely known error, and I believe it has been opened before. But I will leave this open because it is not fixed and makes a good reminder.

**Comment by cyankw** [comment]
I had viewed the source file, although I'm not familiar with the pycrypto package, but is it possible to capture this exception before it made the whole process down? 
Usually, when this exception raised, the whole process went down, and need to start again.

**Comment by deadPix3l** [comment]
it is possible to catch yes. but 1) what to do with the (potentially) corrupted data? 2) how to signal that block was corrupted and 3) it should be determined why it happens.

**Comment by cyankw** [comment]
since the raise of exception is just for a trace info, 
how about capture it and use the [traceback] package to output the error ? it can help to turn the standard exception output info into a string, then, print it.
it is important to get the exception information, but it's not necessary to get the whole process down.
It seems necessary for at least this exception, as this exception always been raise...

it's not a fully solution, but it can make the using a lot more comfortable, there is no need to worry about whether the process will down next minute...

**Comment by deadPix3l** [comment]
it is being debugged currently, and i think i have it almost fixed. that said, i will also work on catching the error and returning to a working state. previously, the error was being caught, but it caused a spiral effect, where after the first one, it would happen every command, and while it wouldn't crash the process, it would make it unusable. Crashing, in this case, is preferable because it signals failure and allows watchdog processes to restart it (if available). the cause for these errors is being pinned down currently, and hopefully will be patched soon.

**Comment by cyankw** [comment]
oh....I see, thx for your patient explain~

**Comment by vesche** [comment]
I've rolled back to AES-256 D-H without GCM. For the time being this should no longer be a problem. If GCM support is still desired, work can be conducted in the `output` branch. More here: https://github.com/vesche/basicRAT/pull/21
